//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lanlords_web_services.Models.db_model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NOOCHEntities : DbContext
    {
        public NOOCHEntities()
            : base("name=NOOCHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankPicture> BankPictures { get; set; }
        public virtual DbSet<Landlord> Landlords { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MemberNotification> MemberNotifications { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MembersIPAddress> MembersIPAddresses { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<PropertyUnit> PropertyUnits { get; set; }
        public virtual DbSet<SynapseBankLoginResult> SynapseBankLoginResults { get; set; }
        public virtual DbSet<SynapseBanksOfMember> SynapseBanksOfMembers { get; set; }
        public virtual DbSet<SynapseCreateOrderResult> SynapseCreateOrderResults { get; set; }
        public virtual DbSet<SynapseCreateUserResult> SynapseCreateUserResults { get; set; }
        public virtual DbSet<SynapseSupportedBank> SynapseSupportedBanks { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
    }
}
